trigger:
  branches:
    include:
      - master
      - v*-prep

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    inputs:
      versionSpec: '12.x'

  - task: Bash@3
    displayName: "Install dependencies"
    inputs:
      filePath: '.azure-pipelines/InstallDependencies.sh'

  - task: Bash@3
    displayName: "Configure Git"
    inputs:
      filePath: '.azure-pipelines/ConfigureGit.sh'

  - task: Bash@3
    displayName: "Start xvfb"
    inputs:
      filePath: '.azure-pipelines/AdditionalSetup.sh'

  - task: Bash@3
    displayName: "Lint & Test"
    inputs:
      filePath: '.azure-pipelines/Test.sh'
    env:
      DISPLAY: ':99.0'

  - task: Bash@3
    displayName: "Build"
    inputs:
      filePath: '.azure-pipelines/Build.sh'
