trigger:
  branches:
    include:
      - master

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: NodeTool@0
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest')
    inputs:
      versionSpec: '12.x'

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest')
    displayName: "Install dependencies"
    inputs:
      filePath: '.azure-pipelines/InstallDependencies.ps1'

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest')
    displayName: "Start xvfb"
    inputs:
      filePath: '.azure-pipelines/AdditionalSetup.ps1'

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest')
    displayName: "Lint & Test"
    inputs:
      filePath: '.azure-pipelines/Test.ps1'
    env:
      DISPLAY: ':99.0'

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest')
    displayName: "Build"
    inputs:
      filePath: '.azure-pipelines/Build.ps1'

  - task: PowerShell@2
    condition: and(succeeded(), eq(variables['Build.Reason'], 'PullRequest')
    displayName: "Create Production Release Tag"
    inputs:
      filePath: '.azure-pipelines/CreateReleaseTag.ps1'
